spring.application.name=api-gateway-service

server.port= 8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#api gateway

# Gateway Service Configuration

spring.main.web-application-type=reactive
# Route configuration (sample hardcoded URIs)
spring.cloud.gateway.routes[0].id=productservice
spring.cloud.gateway.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[1].id=product-dashboard-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/dashboard/**

