spring.application.name=product-dashboard-service

server.port= 8082
#fecthing from external config server 
#spring.cloud.config.uri=optional:configserver:http://localhost:8888

#bootsstrap file getting before the app start

#eureka configuartaion
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.cloud.config.import-check.enabled=false

logging.level.org.springframework.cloud.netflix.eureka=DEBUG
#feign client logs
logging.level.com.dashboard.productDashboard.feign =DEBUG
spring.cloud.openfeign.circuitbreaker.enabled=true
feign.circuitbreaker.enabled=true

#circuite breaker configuartion 

resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.productService.slowCallDurationThreshold=2000